version: "3"
services:
    frontend:
        container_name: stears-test-react
        restart: on-failure
        build: ./client
        stdin_open: true
        tty: true
        expose: 
            - "3000"
        ports: 
            - "3000:3000"
        depends_on: 
            - backend
        links:
            - backend
    backend:
        container_name: stears-test
        build: ./
        expose: 
            - "5000"
        ports: 
            - "5000:5000"
